import type { Project } from './types';

export const initialProjects: Project[] = [
  {
    id: '1',
    title: 'Varkey (The City Of Soul)',
    category: 'Documentaries',
    vimeoId: '528591162',
    description: 'TV Documentary',
    thumbnail: 'https://vumbnail.com/528591162.jpg',
  },
  {
    id: '2',
    title: 'Promo of the series "Tears of Men"',
    category: 'TV Production',
    vimeoId: '524881026',
    description: 'TV Series Promo.',
    thumbnail: 'https://vumbnail.com/524881026.jpg',
  },
  {
    id: '3',
    title: 'A Glimpse from the Heritage Promo',
    category: 'TV Production',
    vimeoId: '524883203',
    description: 'TV Show Promo.',
    thumbnail: 'https://vumbnail.com/524883203.jpg',
  },
  {
    id: '4',
    title: 'Dubai Media Academy Workshop - Day 2',
    category: 'Events',
    vimeoId: '1125810362',
    description: 'Second day highlights from the Dubai Media Academy workshop sessions.',
    thumbnail: 'https://vumbnail.com/1125810362.jpg',
  },
  {
    id: '5',
    title: 'Property Shop Investment Company',
    category: 'Social Media Content',
    vimeoId: '1125810912',
    description: 'Corporate promotional video for Property Shop Investment.',
    thumbnail: 'https://vumbnail.com/1125810912.jpg',
  },
  {
    id: '6',
    title: 'Dubai Media Academy Workshop',
    category: 'Events',
    vimeoId: '1125809997',
    description: 'A workshop held by Dubai Media Academy.',
    thumbnail: 'https://vumbnail.com/1125809997.jpg',
  },
  {
    id: '7',
    title: 'Muntasir Elagami 2025 Showreel',
    category: 'Personal Artistic Work',
    vimeoId: '1107871758',
    description: 'A 2025 showreel of creative work by Muntasir Elagami.',
    thumbnail: 'https://vumbnail.com/1107871758.jpg',
  },
  {
    id: '8',
    title: 'Instagram Content Showcase',
    category: 'Social Media Content',
    vimeoId: '1098329505',
    description: 'Creative Instagram content compilation.',
    thumbnail: 'https://vumbnail.com/1098329505.jpg',
  },
  {
    id: '9',
    title: 'Lotus Car Commercial',
    category: 'TV Production',
    vimeoId: '1098330070',
    description: 'Commercial video for Lotus Cars.',
    thumbnail: 'https://vumbnail.com/1098330070.jpg',
  },
  {
    id: '10',
    title: 'Arab Media Summit Mona Kattan',
    category: 'Events',
    vimeoId: '1098329739',
    description: 'A segment featuring Mona Kattan at the Arab Media Summit.',
    thumbnail: 'https://vumbnail.com/1098329739.jpg',
  },
  {
    id: '11',
    title: 'Arab Media Summit Prizes',
    category: 'Events',
    vimeoId: '1098329579',
    description: 'Coverage of awards at the Arab Media Summit.',
    thumbnail: 'https://vumbnail.com/1098329579.jpg',
  },
  {
    id: '12',
    title: 'Instagram Content by Salma Hibti',
    category: 'Social Media Content',
    vimeoId: '1098329484',
    description: 'A showreel of Instagram content by Ms. Salma Hibti.',
    thumbnail: 'https://vumbnail.com/1098329484.jpg',
  },
  {
    id: '13',
    title: 'UAEU CEO Speech at Gitex',
    category: 'Events',
    vimeoId: '1041819280',
    description: 'UAEU at Gitex.',
    thumbnail: 'https://vumbnail.com/1041819280.jpg',
  },
  {
    id: '14',
    title: 'Real Madrid Foundation Highlight',
    category: 'Social Media Content',
    vimeoId: '1041819630',
    description: 'Real Madrid Foundation Highlight.',
    thumbnail: 'https://vumbnail.com/1041819630.jpg',
  },
  {
    id: '15',
    title: 'Protocom 2024',
    category: 'Events',
    vimeoId: '1041819899',
    description: 'Bio Litec Laser Summit For Proctology.',
    thumbnail: 'https://vumbnail.com/1041819899.jpg',
  },
  {
    id: '16',
    title: 'Protocom 2024',
    category: 'Events',
    vimeoId: '1041820339',
    description: 'Bio Litec Laser Summit For Proctology.',
    thumbnail: 'https://vumbnail.com/1041820339.jpg',
  },
  {
    id: '17',
    title: 'Regenerative Medicine Advances in Coloproctology and Gynecology 2024',
    category: 'Events',
    vimeoId: '1041821533',
    description: 'Highlight of an Event.',
    thumbnail: 'https://vumbnail.com/1041821533.jpg',
  },
  {
    id: '18',
    title: 'Real Madrid Foundation Highlight',
    category: 'Social Media Content',
    vimeoId: '1041822129',
    description: 'Real Madrid Foundation Highlight.',
    thumbnail: 'https://vumbnail.com/1041822129.jpg',
  },
  {
    id: '19',
    title: 'Real Madrid Foundation Highlight',
    category: 'Social Media Content',
    vimeoId: '1041822169',
    description: 'Real Madrid Foundation Highlight.',
    thumbnail: 'https://vumbnail.com/1041822169.jpg',
  },
  {
    id: '20',
    title: 'UAEU Students at Gitex',
    category: 'Social Media Content',
    vimeoId: '1041822199',
    description: 'Student Projects',
    thumbnail: 'https://vumbnail.com/1041822199.jpg',
  },
  {
    id: '21',
    title: 'W.I.N Mena Conference',
    category: 'Events',
    vimeoId: '1041822365',
    description: 'Event Highlight.',
    thumbnail: 'https://vumbnail.com/1041822365.jpg',
  },
  {
    id: '22',
    title: 'Makeup Videography',
    category: 'Personal Artistic Work',
    vimeoId: '1042029456',
    description: 'Shooting The beauty of Makeup',
    thumbnail: 'https://vumbnail.com/1042029456.jpg',
  },
  {
    id: '23',
    title: 'Hamdan Colony Ramadan Nights',
    category: 'Social Media Content',
    vimeoId: '1042029993',
    description: 'Ramadan Nights in Hamdan Colony',
    thumbnail: 'https://vumbnail.com/1042029993.jpg',
  },
  {
    id: '24',
    title: 'Hamdan Colony Ramadan Nights',
    category: 'Social Media Content',
    vimeoId: '1042030043',
    description: 'Ramadan in Dubai',
    thumbnail: 'https://vumbnail.com/1042030043.jpg',
  },
  {
    id: '25',
    title: 'In Photo Space Community (What My Eyes See) ',
    category: 'Personal Artistic Work',
    vimeoId: '1042030090',
    description: 'Ramadan in Dubai',
    thumbnail: 'https://vumbnail.com/1042030090.jpg',
  },
  {
    id: '26',
    title: 'In Photo Space Community',
    category: 'Social Media Content',
    vimeoId: '1042030143',
    description: 'Ramadan Iftar in Dubai.',
    thumbnail: 'https://vumbnail.com/1042030143.jpg',
  },
  {
    id: '27',
    title: 'Highlight on Nikon ZF Camera SOCIAL MEDIA',
    category: 'Social Media Content',
    vimeoId: '1042030879',
    description: 'Product Videography',
    thumbnail: 'https://vumbnail.com/1042030879.jpg',
  },
  {
    id: '28',
    title: 'Highlight on Nikon ZF Camera',
    category: 'Personal Artistic Work',
    vimeoId: '1042030917',
    description: 'Product Videography',
    thumbnail: 'https://vumbnail.com/1042030917.jpg',
  },
  {
    id: '29',
    title: 'Cinematic Portrait Of a Lady',
    category: 'Personal Artistic Work',
    vimeoId: '1042041482',
    description: 'Cinematic Portrait in Al Fahidi Historical Neighbourhood.',
    thumbnail: 'https://vumbnail.com/1042041482.jpg',
  },
  {
    id: '30',
    title: 'Work Space Highlight Video',
    category: 'Personal Artistic Work',
    vimeoId: '1042041532',
    description: 'Cinematic Escape of a Work Space.',
    thumbnail: 'https://vumbnail.com/1042041532.jpg',
  },
  {
    id: '31',
    title: 'Cinematic Makeup Photo Session and Tutorial',
    category: 'Personal Artistic Work',
    vimeoId: '1042041558',
    description: 'Photo Session Highlight.',
    thumbnail: 'https://vumbnail.com/1042041558.jpg',
  },
  {
    id: '32',
    title: 'Timelapse Between The Ages',
    category: 'Social Media Content',
    vimeoId: '530235068',
    description: 'Timelapse in an Ancient Greek City.',
    thumbnail: 'https://vumbnail.com/530235068.jpg',
  },
  {
    id: '33',
    title: 'TV News Report',
    category: 'TV Production',
    vimeoId: '530234471',
    description: 'NEWS Report',
    thumbnail: 'https://vumbnail.com/530234471.jpg',
  },
  {
    id: '34',
    title: 'A Glimpse from the Heritage Episode',
    category: 'TV Production',
    vimeoId: '530236368',
    description: 'TV Show.',
    thumbnail: 'https://vumbnail.com/530236368.jpg',
  },
  {
    id: '35',
    title: 'A Glimpse from the Heritage Episode',
    category: 'TV Production',
    vimeoId: '530242160',
    description: 'TV Show.',
    thumbnail: 'https://vumbnail.com/530242160.jpg',
  },
  {
    id: '36',
    title: 'Event Promo',
    category: 'Events',
    vimeoId: '530106103',
    description: 'Event Highlight.',
    thumbnail: 'https://vumbnail.com/530106103.jpg',
  },
  // Real Estate Videos Below
  {
    id: '37',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051133253',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/zQ2YFMF/thumb-2.jpg',
  },
  {
    id: '38',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051128527',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/SBGkw8R/thumb-3.jpg',
  },
  {
    id: '39',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051128780',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/3pzQTD6/thumb-4.jpg',
  },
  {
    id: '40',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051128977',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/3pzQTD6/thumb-4.jpg',
  },
  {
    id: '41',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051129127',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/ckKpS13/thumb-5.jpg',
  },
  {
    id: '42',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051129259',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/pLTHfdf/thumb-6.jpg',
  },
  {
    id: '43',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051129561',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/wc56cC2/thumb-7.jpg',
  },
  {
    id: '44',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051129689',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/9y62Xxh/thumb-8.jpg',
  },
  {
    id: '45',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051129830',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/sjFVTD2/thumb-9.jpg',
  },
  {
    id: '46',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051130018',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/k3vZrc2/thumb-10.jpg',
  },
  {
    id: '47',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051130218',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/Jz9q0Hz/thumb-11.jpg',
  },
  {
    id: '48',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051130409',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/DbbpwYP/thumb-12.jpg',
  },
  {
    id: '49',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051130826',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/nLTcSb7/thumb-13.jpg',
  },
  {
    id: '50',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051131888',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/stgZJ1C/thumb-14.jpg',
  },
  {
    id: '51',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051132513',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/bXyF4gS/thumb-15.jpg',
  },
  {
    id: '52',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051132676',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/ZLbp7QT/thumb-16.jpg',
  },
  {
    id: '53',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051132861',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/LtLy2wZ/thumb-17.jpg',
  },
  {
    id: '54',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051132967',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/fMsgV1j/thumb-18.jpg',
  },
  {
    id: '55',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051133074',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/HFbvG0G/thumb-19.jpg',
  },
  {
    id: '56',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051133140',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/xF16Gbp/thumb-20.jpg',
  },
  {
    id: '57',
    title: 'Mackerel Tower (Real Estate Video)',
    category: 'Social Media Content',
    vimeoId: '1051133344',
    description: 'Real Estate Video.',
    thumbnail: 'https://i.ibb.co/L0LQWQj/thumb-21.jpg',
  },
];
